window.allExams = window.allExams || {};
window.allExams["exam11"] = {
    id: "exam11",
    title: "EPS-TOPIK Complete Word Meaning Test (Exam 11)",
    subtitle: "All Vocabulary Words from 38 Pictures",
    badge: "실전 연습 (Practice)",
    description: "제공된 모든 38장의 사진에 등장하는 단어 및 표현을 1:1 뜻 매칭 형식으로 완벽하게 테스트합니다.",
    questions: [
        { id: 1, type: "text", title: "1. 다음", word: "다음", options: ["1. Follow / Next", "2. Before / Previous", "3. Test / Exam", "4. Air / Atmosphere"], answer: 0 },
        { id: 2, type: "text", title: "2. 그림", word: "그림", options: ["1. Picture / Drawing", "2. Writing / Letter", "3. Sound / Noise", "4. Music / Song"], answer: 0 },
        { id: 3, type: "text", title: "3. 보다", word: "보다", options: ["1. To look at / See", "2. To listen / Hear", "3. To speak / Talk", "4. To write / Draw"], answer: 0 },
        { id: 4, type: "text", title: "4. 맞다", word: "맞다", options: ["1. To be correct / Right", "2. To be wrong / Incorrect", "3. To be bad / Poor", "4. To be difficult"], answer: 0 },
        { id: 5, type: "text", title: "5. 단어", word: "단어", options: ["1. Word", "2. Sentence", "3. Paragraph", "4. Letter"], answer: 0 },
        { id: 6, type: "text", title: "6. 문장", word: "문장", options: ["1. Sentence", "2. Word", "3. Question", "4. Answer"], answer: 0 },
        { id: 7, type: "text", title: "7. 고르다", word: "고르다", options: ["1. To choose / Select", "2. To collect / Gather", "3. To throw away", "4. To change"], answer: 0 },
        { id: 8, type: "text", title: "8. 컵", word: "컵", options: ["1. Cup", "2. Bowl", "3. Pot", "4. Spoon"], answer: 0 },
        { id: 9, type: "text", title: "9. 그릇", word: "그릇", options: ["1. Bowl / Dish", "2. Cup", "3. Spoon", "4. Chopsticks"], answer: 0 },
        { id: 10, type: "text", title: "10. 냄비", word: "냄비", options: ["1. Pot / Saucepan", "2. Frying pan", "3. Kettle", "4. Plate"], answer: 0 },
        { id: 11, type: "text", title: "11. 젓가락", word: "젓가락", options: ["1. Chopsticks", "2. Spoon", "3. Fork", "4. Knife"], answer: 0 },
        { id: 12, type: "text", title: "12. 서류", word: "서류", options: ["1. Document / Paper", "2. Book", "3. Notebook", "4. Envelope"], answer: 0 },
        { id: 13, type: "text", title: "13. 찢다", word: "찢다", options: ["1. To tear / Rip", "2. To cut", "3. To fold", "4. To glue"], answer: 0 },
        { id: 14, type: "text", title: "14. 도장", word: "도장", options: ["1. Stamp / Seal", "2. Signature", "3. Sticker", "4. Receipt"], answer: 0 },
        { id: 15, type: "text", title: "15. 찍다", word: "찍다", options: ["1. To stamp / Print / Take a picture", "2. To erase", "3. To write", "4. To cut"], answer: 0 },
        { id: 16, type: "text", title: "16. 서명하다", word: "서명하다", options: ["1. To sign", "2. To stamp", "3. To write a letter", "4. To read"], answer: 0 },
        { id: 17, type: "text", title: "17. 복사하다", word: "복사하다", options: ["1. To copy / Duplicate", "2. To print", "3. To scan", "4. To delete"], answer: 0 },
        { id: 18, type: "text", title: "18. 비상구", word: "비상구", options: ["1. Emergency exit", "2. Entrance", "3. Elevator", "4. Stairs"], answer: 0 },
        { id: 19, type: "text", title: "19. 방향", word: "방향", options: ["1. Direction", "2. Location", "3. Distance", "4. Speed"], answer: 0 },
        { id: 20, type: "text", title: "20. 나타내다", word: "나타내다", options: ["1. To indicate / Show", "2. To hide", "3. To change", "4. To disappear"], answer: 0 },
        { id: 21, type: "text", title: "21. 소화기", word: "소화기", options: ["1. Fire extinguisher", "2. Heater", "3. Air conditioner", "4. Fan"], answer: 0 },
        { id: 22, type: "text", title: "22. 위치", word: "위치", options: ["1. Location / Position", "2. Direction", "3. Area", "4. Building"], answer: 0 },
        { id: 23, type: "text", title: "23. 전기", word: "전기", options: ["1. Electricity", "2. Water", "3. Gas", "4. Fire"], answer: 0 },
        { id: 24, type: "text", title: "24. 위험", word: "위험", options: ["1. Danger", "2. Safety", "3. Warning", "4. Caution"], answer: 0 },
        { id: 25, type: "text", title: "25. 손", word: "손", options: ["1. Hand", "2. Foot", "3. Arm", "4. Leg"], answer: 0 },
        { id: 26, type: "text", title: "26. 씻기", word: "씻기", options: ["1. Washing", "2. Cleaning", "3. Wiping", "4. Drying"], answer: 0 },
        { id: 27, type: "text", title: "27. 두", word: "두", options: ["1. Two", "2. One", "3. Three", "4. Four"], answer: 0 },
        { id: 28, type: "text", title: "28. 사람", word: "사람", options: ["1. Person / People", "2. Animal", "3. Thing", "4. Place"], answer: 0 },
        { id: 29, type: "text", title: "29. 회의", word: "회의", options: ["1. Meeting / Conference", "2. Meal", "3. Rest", "4. Exercise"], answer: 0 },
        { id: 30, type: "text", title: "30. 식사", word: "식사", options: ["1. Meal / Dining", "2. Meeting", "3. Work", "4. Study"], answer: 0 },
        { id: 31, type: "text", title: "31. 청소", word: "청소", options: ["1. Cleaning", "2. Cooking", "3. Washing clothes", "4. Shopping"], answer: 0 },
        { id: 32, type: "text", title: "32. 운동", word: "운동", options: ["1. Exercise / Workout", "2. Rest", "3. Sleep", "4. Walk"], answer: 0 },
        { id: 33, type: "text", title: "33. 빈칸", word: "빈칸", options: ["1. Blank space", "2. Full line", "3. Margin", "4. End page"], answer: 0 },
        { id: 34, type: "text", title: "34. 들어가다", word: "들어가다", options: ["1. To enter / Go into", "2. To go out", "3. To come back", "4. To pass by"], answer: 0 },
        { id: 35, type: "text", title: "35. 가장", word: "가장", options: ["1. Most / Best", "2. Least", "3. Some", "4. All"], answer: 0 },
        { id: 36, type: "text", title: "36. 알맞다", word: "알맞다", options: ["1. To be appropriate / Suitable", "2. To be wrong", "3. To be difficult", "4. To be easy"], answer: 0 },
        { id: 37, type: "text", title: "37. 매일", word: "매일", options: ["1. Every day", "2. Every week", "3. Every month", "4. Every year"], answer: 0 },
        { id: 38, type: "text", title: "38. 아침", word: "아침", options: ["1. Morning", "2. Afternoon", "3. Evening", "4. Night"], answer: 0 },
        { id: 39, type: "text", title: "39. 8시", word: "8시", options: ["1. 8 o'clock", "2. 7 o'clock", "3. 9 o'clock", "4. 10 o'clock"], answer: 0 },
        { id: 40, type: "text", title: "40. 회사", word: "회사", options: ["1. Company / Office", "2. School", "3. Hospital", "4. Bank"], answer: 0 },
        { id: 41, type: "text", title: "41. 출근하다", word: "출근하다", options: ["1. To go to work", "2. To leave work", "3. To be late", "4. To be absent"], answer: 0 },
        { id: 42, type: "text", title: "42. 그래서", word: "그래서", options: ["1. So / Therefore", "2. But / However", "3. Or", "4. And then"], answer: 0 },
        { id: 43, type: "text", title: "43. 항상", word: "항상", options: ["1. Always", "2. Sometimes", "3. Never", "4. Rarely"], answer: 0 },
        { id: 44, type: "text", title: "44. 일찍", word: "일찍", options: ["1. Early", "2. Late", "3. Fast", "4. Slow"], answer: 0 },
        { id: 45, type: "text", title: "45. 일어나다", word: "일어나다", options: ["1. To get up / Wake up", "2. To lie down", "3. To sit down", "4. To sleep"], answer: 0 },
        { id: 46, type: "text", title: "46. 퇴근하다", word: "퇴근하다", options: ["1. To leave work", "2. To go to work", "3. To take a break", "4. To change jobs"], answer: 0 },
        { id: 47, type: "text", title: "47. 결근하다", word: "결근하다", options: ["1. To be absent from work", "2. To be late", "3. To work overtime", "4. To take vacation"], answer: 0 },
        { id: 48, type: "text", title: "48. 조퇴하다", word: "조퇴하다", options: ["1. To leave work early", "2. To arrive early", "3. To stay late", "4. To take a day off"], answer: 0 },
        { id: 49, type: "text", title: "49. 배", word: "배", options: ["1. Stomach / Ship / Pear", "2. Hand", "3. Head", "4. Foot"], answer: 0 },
        { id: 50, type: "text", title: "50. 아프다", word: "아프다", options: ["1. To be sick / Hurt", "2. To be happy", "3. To be healthy", "4. To be tired"], answer: 0 },
        { id: 51, type: "text", title: "51. 병원", word: "병원", options: ["1. Hospital", "2. Pharmacy", "3. Bank", "4. Post office"], answer: 0 },
        { id: 52, type: "text", title: "52. 가다", word: "가다", options: ["1. To go", "2. To come", "3. To stay", "4. To return"], answer: 0 },
        { id: 53, type: "text", title: "53. 오후", word: "오후", options: ["1. Afternoon", "2. Morning", "3. Midnight", "4. Noon"], answer: 0 },
        { id: 54, type: "text", title: "54. 지각하다", word: "지각하다", options: ["1. To be late", "2. To be early", "3. To be on time", "4. To be absent"], answer: 0 },
        { id: 55, type: "text", title: "55. 야근하다", word: "야근하다", options: ["1. To work overtime", "2. To leave early", "3. To take a break", "4. To sleep"], answer: 0 },
        { id: 56, type: "text", title: "56. 이번", word: "이번", options: ["1. This time / Current", "2. Last time", "3. Next time", "4. First time"], answer: 0 },
        { id: 57, type: "text", title: "57. 달", word: "달", options: ["1. Month / Moon", "2. Sun", "3. Star", "4. Sky"], answer: 0 },
        { id: 58, type: "text", title: "58. 월급", word: "월급", options: ["1. Salary / Monthly pay", "2. Bonus", "3. Tax", "4. Savings"], answer: 0 },
        { id: 59, type: "text", title: "59. 받다", word: "받다", options: ["1. To receive", "2. To give", "3. To send", "4. To take away"], answer: 0 },
        { id: 60, type: "text", title: "60. 고향", word: "고향", options: ["1. Hometown", "2. Capital", "3. Foreign country", "4. City"], answer: 0 },
        { id: 61, type: "text", title: "61. 가족", word: "가족", options: ["1. Family", "2. Friend", "3. Colleague", "4. Neighbor"], answer: 0 },
        { id: 62, type: "text", title: "62. 송금하다", word: "송금하다", options: ["1. To remit / Transfer money", "2. To withdraw money", "3. To borrow money", "4. To exchange money"], answer: 0 },
        { id: 63, type: "text", title: "63. 청구하다", word: "청구하다", options: ["1. To claim / Charge", "2. To pay", "3. To refund", "4. To save"], answer: 0 },
        { id: 64, type: "text", title: "64. 환급하다", word: "환급하다", options: ["1. To refund", "2. To charge", "3. To transfer", "4. To borrow"], answer: 0 },
        { id: 65, type: "text", title: "65. 적금하다", word: "적금하다", options: ["1. To save money", "2. To spend money", "3. To lose money", "4. To borrow money"], answer: 0 },
        { id: 66, type: "text", title: "66. 작업장", word: "작업장", options: ["1. Workplace / Workshop", "2. Office", "3. Restroom", "4. Cafeteria"], answer: 0 },
        { id: 67, type: "text", title: "67. 소음", word: "소음", options: ["1. Noise", "2. Quiet", "3. Music", "4. Voice"], answer: 0 },
        { id: 68, type: "text", title: "68. 심하다", word: "심하다", options: ["1. To be severe / Extreme", "2. To be light", "3. To be weak", "4. To be simple"], answer: 0 },
        { id: 69, type: "text", title: "69. 귀마개", word: "귀마개", options: ["1. Earplugs", "2. Safety goggles", "3. Dust mask", "4. Safety gloves"], answer: 0 },
        { id: 70, type: "text", title: "70. 청력", word: "청력", options: ["1. Hearing", "2. Sight", "3. Touch", "4. Smell"], answer: 0 },
        { id: 71, type: "text", title: "71. 보호하다", word: "보호하다", options: ["1. To protect", "2. To destroy", "3. To injure", "4. To ignore"], answer: 0 },
        { id: 72, type: "text", title: "72. 위하다", word: "위하다", options: ["1. To do for the sake of / For", "2. To against", "3. To avoid", "4. To follow"], answer: 0 },
        { id: 73, type: "text", title: "73. 착용하다", word: "착용하다", options: ["1. To wear / Put on", "2. To take off", "3. To wash", "4. To buy"], answer: 0 },
        { id: 74, type: "text", title: "74. 제거하다", word: "제거하다", options: ["1. To remove / Eliminate", "2. To attach", "3. To build", "4. To clean"], answer: 0 },
        { id: 75, type: "text", title: "75. 분리하다", word: "분리하다", options: ["1. To separate / Divide", "2. To combine", "3. To mix", "4. To collect"], answer: 0 },
        { id: 76, type: "text", title: "76. 세척하다", word: "세척하다", options: ["1. To wash / Clean", "2. To dirty", "3. To dry", "4. To break"], answer: 0 },
        { id: 77, type: "text", title: "77. 상사", word: "상사", options: ["1. Boss / Superior", "2. Subordinate", "3. Colleague", "4. Customer"], answer: 0 },
        { id: 78, type: "text", title: "78. 부탁하다", word: "부탁하다", options: ["1. To ask a favor / Request", "2. To order", "3. To refuse", "4. To promise"], answer: 0 },
        { id: 79, type: "text", title: "79. 보고서", word: "보고서", options: ["1. Report", "2. Letter", "3. Diary", "4. Novel"], answer: 0 },
        { id: 80, type: "text", title: "80. 아직", word: "아직", options: ["1. Still / Yet", "2. Already", "3. Always", "4. Never"], answer: 0 },
        { id: 81, type: "text", title: "81. 다", word: "다", options: ["1. All / Completely", "2. None", "3. Part", "4. Some"], answer: 0 },
        { id: 82, type: "text", title: "82. 못", word: "못", options: ["1. Cannot", "2. Can", "3. Must", "4. Should"], answer: 0 },
        { id: 83, type: "text", title: "83. 쓰다", word: "쓰다", options: ["1. To write / Use / Wear", "2. To read", "3. To speak", "4. To listen"], answer: 0 },
        { id: 84, type: "text", title: "84. 오늘", word: "오늘", options: ["1. Today", "2. Yesterday", "3. Tomorrow", "4. Every day"], answer: 0 },
        { id: 85, type: "text", title: "85. 야근", word: "야근", options: ["1. Overtime work", "2. Day shift", "3. Weekend work", "4. Vacation"], answer: 0 },
        { id: 86, type: "text", title: "86. 휴가", word: "휴가", options: ["1. Vacation / Leave", "2. Resignation", "3. Absence", "4. Business trip"], answer: 0 },
        { id: 87, type: "text", title: "87. 결근", word: "결근", options: ["1. Absence from work", "2. Tardiness", "3. Early leave", "4. Overtime"], answer: 0 },
        { id: 88, type: "text", title: "88. 지각", word: "지각", options: ["1. Lateness", "2. Being early", "3. Absence", "4. Resignation"], answer: 0 },
        { id: 89, type: "text", title: "89. 부장님", word: "부장님", options: ["1. Department head / General manager", "2. CEO", "3. Supervisor", "4. Colleague"], answer: 0 },
        { id: 90, type: "text", title: "90. 신청하다", word: "신청하다", options: ["1. To apply / Request", "2. To cancel", "3. To approve", "4. To reject"], answer: 0 },
        { id: 91, type: "text", title: "91. 사직", word: "사직", options: ["1. Resignation", "2. Dismissal", "3. Promotion", "4. Transfer"], answer: 0 },
        { id: 92, type: "text", title: "92. 업무", word: "업무", options: ["1. Work / Business / Task", "2. Rest", "3. Hobby", "4. Exercise"], answer: 0 },
        { id: 93, type: "text", title: "93. 새로", word: "새로", options: ["1. Newly / Freshly", "2. Again", "3. Always", "4. Usually"], answer: 0 },
        { id: 94, type: "text", title: "94. 입사한", word: "입사한", options: ["1. Joined a company", "2. Left a company", "3. Promoted", "4. Transferred"], answer: 0 },
        { id: 95, type: "text", title: "95. 직원", word: "직원", options: ["1. Employee / Staff", "2. Boss", "3. Customer", "4. Owner"], answer: 0 },
        { id: 96, type: "text", title: "96. 처음에", word: "처음에", options: ["1. At first", "2. Finally", "3. Always", "4. Suddenly"], answer: 0 },
        { id: 97, type: "text", title: "97. 낯설다", word: "낯설다", options: ["1. To be unfamiliar", "2. To be familiar", "3. To be comfortable", "4. To be easy"], answer: 0 },
        { id: 98, type: "text", title: "98. 실수", word: "실수", options: ["1. Mistake / Error", "2. Success", "3. Practice", "4. Habit"], answer: 0 },
        { id: 99, type: "text", title: "99. 하다", word: "하다", options: ["1. To do", "2. To be", "3. To go", "4. To see"], answer: 0 },
        { id: 100, type: "text", title: "100. 그러므로", word: "그러므로", options: ["1. Therefore / Thus", "2. However", "3. Moreover", "4. Meanwhile"], answer: 0 },
        { id: 101, type: "text", title: "101. 선배", word: "선배", options: ["1. Senior colleague", "2. Junior colleague", "3. Manager", "4. Newcomer"], answer: 0 },
        { id: 102, type: "text", title: "102. 가르쳐 주다", word: "가르쳐 주다", options: ["1. To teach / Show", "2. To hide", "3. To scold", "4. To ignore"], answer: 0 },
        { id: 103, type: "text", title: "103. 무시하다", word: "무시하다", options: ["1. To ignore", "2. To respect", "3. To help", "4. To praise"], answer: 0 },
        { id: 104, type: "text", title: "104. 혼내다", word: "혼내다", options: ["1. To scold", "2. To praise", "3. To help", "4. To comfort"], answer: 0 },
        { id: 105, type: "text", title: "105. 비교하다", word: "비교하다", options: ["1. To compare", "2. To mix", "3. To separate", "4. To collect"], answer: 0 },
        { id: 106, type: "text", title: "106. 나머지", word: "나머지", options: ["1. The rest / Remaining", "2. The whole", "3. The first", "4. The last"], answer: 0 },
        { id: 107, type: "text", title: "107. 셋", word: "셋", options: ["1. Three", "2. Two", "3. Four", "4. Five"], answer: 0 },
        { id: 108, type: "text", title: "108. 관계", word: "관계", options: ["1. Relationship", "2. Difference", "3. Problem", "4. Answer"], answer: 0 },
        { id: 109, type: "text", title: "109. 다르다", word: "다르다", options: ["1. To be different", "2. To be same", "3. To be similar", "4. To be correct"], answer: 0 },
        { id: 110, type: "text", title: "110. 설명", word: "설명", options: ["1. Explanation", "2. Question", "3. Answer", "4. Example"], answer: 0 },
        { id: 111, type: "text", title: "111. 스스로", word: "스스로", options: ["1. By oneself / Voluntarily", "2. Forcefully", "3. Together", "4. Suddenly"], answer: 0 },
        { id: 112, type: "text", title: "112. 그만두다", word: "그만두다", options: ["1. To quit / Stop", "2. To start", "3. To continue", "4. To try"], answer: 0 },
        { id: 113, type: "text", title: "113. 해고", word: "해고", options: ["1. Dismissal / Firing", "2. Resignation", "3. Promotion", "4. Transfer"], answer: 0 },
        { id: 114, type: "text", title: "114. 전근", word: "전근", options: ["1. Transfer of work location", "2. Resignation", "3. Retirement", "4. Promotion"], answer: 0 },
        { id: 115, type: "text", title: "115. 밑줄 친", word: "밑줄 친", options: ["1. Underlined", "2. Crossed out", "3. Circled", "4. Bolded"], answer: 0 },
        { id: 116, type: "text", title: "116. 부분", word: "부분", options: ["1. Part / Section", "2. Whole", "3. Beginning", "4. End"], answer: 0 },
        { id: 117, type: "text", title: "117. 어제", word: "어제", options: ["1. Yesterday", "2. Today", "3. Tomorrow", "4. Last week"], answer: 0 },
        { id: 118, type: "text", title: "118. 제출하다", word: "제출하다", options: ["1. To submit / Hand in", "2. To take back", "3. To throw away", "4. To keep"], answer: 0 },
        { id: 119, type: "text", title: "119. 참석하다", word: "참석하다", options: ["1. To attend", "2. To be absent", "3. To leave", "4. To watch"], answer: 0 },
        { id: 120, type: "text", title: "120. 동안에", word: "동안에", options: ["1. During / While", "2. Before", "3. After", "4. Because"], answer: 0 },
        { id: 121, type: "text", title: "121. 열심히", word: "열심히", options: ["1. Hard / Diligently", "2. Lazily", "3. Slowly", "4. Quickly"], answer: 0 },
        { id: 122, type: "text", title: "122. 내다", word: "내다", options: ["1. To pay / Submit", "2. To take", "3. To keep", "4. To receive"], answer: 0 },
        { id: 123, type: "text", title: "123. 동료", word: "동료", options: ["1. Colleague / Coworker", "2. Boss", "3. Friend", "4. Family"], answer: 0 },
        { id: 124, type: "text", title: "124. 고맙다", word: "고맙다", options: ["1. To be thankful", "2. To be sorry", "3. To be sad", "4. To be angry"], answer: 0 },
        { id: 125, type: "text", title: "125. 새", word: "새", options: ["1. New", "2. Old", "3. Big", "4. Small"], answer: 0 },
        { id: 126, type: "text", title: "126. 기계", word: "기계", options: ["1. Machine", "2. Tool", "3. Material", "4. Product"], answer: 0 },
        { id: 127, type: "text", title: "127. 방법", word: "방법", options: ["1. Method / Way", "2. Result", "3. Reason", "4. Purpose"], answer: 0 },
        { id: 128, type: "text", title: "128. 배우다", word: "배우다", options: ["1. To learn", "2. To teach", "3. To forget", "4. To practice"], answer: 0 },
        { id: 129, type: "text", title: "129. 지난주", word: "지난주", options: ["1. Last week", "2. This week", "3. Next week", "4. Last month"], answer: 0 },
        { id: 130, type: "text", title: "130. 안전", word: "안전", options: ["1. Safety", "2. Danger", "3. Warning", "4. Accident"], answer: 0 },
        { id: 131, type: "text", title: "131. 교육", word: "교육", options: ["1. Education / Training", "2. Test", "3. Work", "4. Rest"], answer: 0 },
        { id: 132, type: "text", title: "132. 빠지다", word: "빠지다", options: ["1. To be absent / Skip", "2. To attend", "3. To join", "4. To finish"], answer: 0 },
        { id: 133, type: "text", title: "133. 안전모", word: "안전모", options: ["1. Safety helmet", "2. Dust mask", "3. Safety shoes", "4. Safety gloves"], answer: 0 },
        { id: 134, type: "text", title: "134. 안", word: "안", options: ["1. Not", "2. Yes", "3. Always", "4. Very"], answer: 0 },
        { id: 135, type: "text", title: "135. 다치다", word: "다치다", options: ["1. To get hurt / Injured", "2. To heal", "3. To protect", "4. To fix"], answer: 0 },
        { id: 136, type: "text", title: "136. 안내문", word: "안내문", options: ["1. Notice / Guide", "2. Contract", "3. Report", "4. Letter"], answer: 0 },
        { id: 137, type: "text", title: "137. 읽다", word: "읽다", options: ["1. To read", "2. To write", "3. To speak", "4. To listen"], answer: 0 },
        { id: 138, type: "text", title: "138. 질문", word: "질문", options: ["1. Question", "2. Answer", "3. Example", "4. Problem"], answer: 0 },
        { id: 139, type: "text", title: "139. 답하다", word: "답하다", options: ["1. To answer", "2. To ask", "3. To listen", "4. To read"], answer: 0 },
        { id: 140, type: "text", title: "140. 외국인", word: "외국인", options: ["1. Foreigner", "2. Citizen", "3. Guide", "4. Worker"], answer: 0 },
        { id: 141, type: "text", title: "141. 근로자", word: "근로자", options: ["1. Worker / Laborer", "2. Employer", "3. Customer", "4. Manager"], answer: 0 },
        { id: 142, type: "text", title: "142. 건강보험", word: "건강보험", options: ["1. Health insurance", "2. Fire insurance", "3. Life insurance", "4. Car insurance"], answer: 0 },
        { id: 143, type: "text", title: "143. 가입", word: "가입", options: ["1. Subscription / Joining", "2. Withdrawal", "3. Cancellation", "4. Completion"], answer: 0 },
        { id: 144, type: "text", title: "144. 대상", word: "대상", options: ["1. Target / Subject", "2. Result", "3. Method", "4. Period"], answer: 0 },
        { id: 145, type: "text", title: "145. 사업장", word: "사업장", options: ["1. Workplace / Business site", "2. Office", "3. Home", "4. School"], answer: 0 },
        { id: 146, type: "text", title: "146. 고용된", word: "고용된", options: ["1. Employed", "2. Fired", "3. Retired", "4. Resigned"], answer: 0 },
        { id: 147, type: "text", title: "147. 보험료", word: "보험료", options: ["1. Insurance premium", "2. Salary", "3. Tax", "4. Bonus"], answer: 0 },
        { id: 148, type: "text", title: "148. 부담", word: "부담", options: ["1. Burden / Payment responsibility", "2. Benefit", "3. Profit", "4. Reward"], answer: 0 },
        { id: 149, type: "text", title: "149. 적용", word: "적용", options: ["1. Application / Coverage", "2. Cancellation", "3. Exclusion", "4. Delay"], answer: 0 },
        { id: 150, type: "text", title: "150. 시작", word: "시작", options: ["1. Start / Beginning", "2. End", "3. Middle", "4. Pause"], answer: 0 },
        { id: 151, type: "text", title: "151. 입사일", word: "입사일", options: ["1. Date of joining a company", "2. Resignation date", "3. Payday", "4. Vacation date"], answer: 0 },
        { id: 152, type: "text", title: "152. 후", word: "후", options: ["1. After / Later", "2. Before", "3. During", "4. Always"], answer: 0 },
        { id: 153, type: "text", title: "153. 사용자", word: "사용자", options: ["1. Employer / User", "2. Employee", "3. Customer", "4. Visitor"], answer: 0 },
        { id: 154, type: "text", title: "154. 신고", word: "신고", options: ["1. Report / Declaration", "2. Application", "3. Permission", "4. Request"], answer: 0 },
        { id: 155, type: "text", title: "155. 주의", word: "주의", options: ["1. Caution / Attention", "2. Safety", "3. Danger", "4. Warning"], answer: 0 },
        { id: 156, type: "text", title: "156. 직장", word: "직장", options: ["1. Workplace / Job", "2. Home", "3. School", "4. Hospital"], answer: 0 },
        { id: 157, type: "text", title: "157. 옮기다", word: "옮기다", options: ["1. To move / Transfer", "2. To stay", "3. To fix", "4. To break"], answer: 0 },
        { id: 158, type: "text", title: "158. 다시", word: "다시", options: ["1. Again", "2. Never", "3. Always", "4. Sometimes"], answer: 0 },
        { id: 159, type: "text", title: "159. 산업재해", word: "산업재해", options: ["1. Industrial accident", "2. Traffic accident", "3. Natural disaster", "4. Fire accident"], answer: 0 },
        { id: 160, type: "text", title: "160. 보상", word: "보상", options: ["1. Compensation", "2. Punishment", "3. Fine", "4. Fee"], answer: 0 },
        { id: 161, type: "text", title: "161. 산재", word: "산재", options: ["1. Industrial accident (abbreviation)", "2. Health insurance", "3. Employment insurance", "4. Pension"], answer: 0 },
        { id: 162, type: "text", title: "162. 당하다", word: "당하다", options: ["1. To suffer / Experience", "2. To enjoy", "3. To succeed", "4. To win"], answer: 0 },
        { id: 163, type: "text", title: "163. 치료", word: "치료", options: ["1. Treatment / Medical care", "2. Examination", "3. Operation", "4. Prescription"], answer: 0 },
        { id: 164, type: "text", title: "164. 지정", word: "지정", options: ["1. Designation / Appointment", "2. Cancellation", "3. Selection", "4. Recommendation"], answer: 0 },
        { id: 165, type: "text", title: "165. 무료", word: "무료", options: ["1. Free of charge", "2. Paid", "3. Expensive", "4. Cheap"], answer: 0 },
        { id: 166, type: "text", title: "166. 고용노동부", word: "고용노동부", options: ["1. Ministry of Employment and Labor", "2. Ministry of Health", "3. Ministry of Education", "4. Ministry of Finance"], answer: 0 },
        { id: 167, type: "text", title: "167. 근로복지공단", word: "근로복지공단", options: ["1. Korea Workers' Compensation and Welfare Service", "2. National Health Insurance Service", "3. Immigration Office", "4. Labor Office"], answer: 0 },
        { id: 168, type: "text", title: "168. 진단서", word: "진단서", options: ["1. Medical certificate", "2. Contract", "3. Report", "4. Receipt"], answer: 0 },
        { id: 169, type: "text", title: "169. 재해", word: "재해", options: ["1. Disaster / Accident", "2. Disease", "3. Injury", "4. Pain"], answer: 0 },
        { id: 170, type: "text", title: "170. 경위서", word: "경위서", options: ["1. Statement of details", "2. Medical report", "3. Employment contract", "4. Resignation letter"], answer: 0 },
        { id: 171, type: "text", title: "171. 근로계약서", word: "근로계약서", options: ["1. Employment contract", "2. Business report", "3. Medical certificate", "4. Tax form"], answer: 0 },
        { id: 172, type: "text", title: "172. 처리", word: "처리", options: ["1. Processing / Handling", "2. Planning", "3. Application", "4. Decision"], answer: 0 },
        { id: 173, type: "text", title: "173. 기간", word: "기간", options: ["1. Period / Term", "2. Date", "3. Time", "4. Deadline"], answer: 0 },
        { id: 174, type: "text", title: "174. 약", word: "약", options: ["1. About / Approximately", "2. Exactly", "3. Under", "4. Over"], answer: 0 },
        { id: 175, type: "text", title: "175. 이내", word: "이내", options: ["1. Within", "2. Over / Beyond", "3. Before", "4. After"], answer: 0 },
        { id: 176, type: "text", title: "176. 결정", word: "결정", options: ["1. Decision / Determination", "2. Application", "3. Report", "4. Request"], answer: 0 },
        { id: 177, type: "text", title: "177. 기한", word: "기한", options: ["1. Deadline / Time limit", "2. Period", "3. Start date", "4. Schedule"], answer: 0 },
        { id: 178, type: "text", title: "178. 사고", word: "사고", options: ["1. Accident", "2. Success", "3. Mistake", "4. Problem"], answer: 0 },
        { id: 179, type: "text", title: "179. 발생일", word: "발생일", options: ["1. Date of occurrence", "2. Payday", "3. Expiration date", "4. Application date"], answer: 0 },
        { id: 180, type: "text", title: "180. 부터", word: "부터", options: ["1. From", "2. To", "3. Until", "4. In"], answer: 0 },
        { id: 181, type: "text", title: "181. 3년", word: "3년", options: ["1. 3 years", "2. 3 months", "3. 3 weeks", "4. 3 days"], answer: 0 },
        { id: 182, type: "text", title: "182. 회식", word: "회식", options: ["1. Company dinner / Get-together", "2. Business trip", "3. Overtime work", "4. Morning meeting"], answer: 0 },
        { id: 183, type: "text", title: "183. 술", word: "술", options: ["1. Alcohol / Liquor", "2. Water", "3. Tea", "4. Juice"], answer: 0 },
        { id: 184, type: "text", title: "184. 친해지다", word: "친해지다", options: ["1. To become close / Friendly", "2. To fight", "3. To become stranger", "4. To separate"], answer: 0 },
        { id: 185, type: "text", title: "185. 날짜", word: "날짜", options: ["1. Date", "2. Time", "3. Place", "4. Person"], answer: 0 },
        { id: 186, type: "text", title: "186. 정하다", word: "정하다", options: ["1. To decide / Fix", "2. To change", "3. To cancel", "4. To ask"], answer: 0 },
        { id: 187, type: "text", title: "187. 최근", word: "최근", options: ["1. Recently / Lately", "2. In the past", "3. In the future", "4. Always"], answer: 0 },
        { id: 188, type: "text", title: "188. 의견", word: "의견", options: ["1. Opinion / View", "2. Question", "3. Answer", "4. Fact"], answer: 0 },
        { id: 189, type: "text", title: "189. 물어보다", word: "물어보다", options: ["1. To ask", "2. To answer", "3. To tell", "4. To listen"], answer: 0 },
        { id: 190, type: "text", title: "190. 건강", word: "건강", options: ["1. Health", "2. Disease", "3. Pain", "4. Fatigue"], answer: 0 },
        { id: 191, type: "text", title: "191. 문제", word: "문제", options: ["1. Problem / Issue", "2. Solution", "3. Answer", "4. Success"], answer: 0 },
        { id: 192, type: "text", title: "192. 미리", word: "미리", options: ["1. In advance", "2. Later", "3. Suddenly", "4. Always"], answer: 0 },
        { id: 193, type: "text", title: "193. 4대 보험", word: "4대 보험", options: ["1. Four major public insurances", "2. Private insurance", "3. Life insurance", "4. Car insurance"], answer: 0 },
        { id: 194, type: "text", title: "194. 국민연금", word: "국민연금", options: ["1. National Pension", "2. Health insurance", "3. Employment insurance", "4. Industrial accident insurance"], answer: 0 },
        { id: 195, type: "text", title: "195. 고용보험", word: "고용보험", options: ["1. Employment insurance", "2. National Pension", "3. Health insurance", "4. Industrial accident insurance"], answer: 0 },
        { id: 196, type: "text", title: "196. 산재보험", word: "산재보험", options: ["1. Industrial Accident Compensation Insurance", "2. Health insurance", "3. National Pension", "4. Employment insurance"], answer: 0 },
        { id: 197, type: "text", title: "197. 비용", word: "비용", options: ["1. Cost / Expense", "2. Salary", "3. Profit", "4. Tax"], answer: 0 },
        { id: 198, type: "text", title: "198. 전액", word: "전액", options: ["1. Total amount / Full sum", "2. Half price", "3. Part payment", "4. Free"], answer: 0 },
        { id: 199, type: "text", title: "199. 나누다", word: "나누다", options: ["1. To share / Divide", "2. To combine", "3. To collect", "4. To save"], answer: 0 },
        { id: 200, type: "text", title: "200. 아프다", word: "아프다", options: ["1. To be sick / Hurt", "2. To be happy", "3. To be healthy", "4. To be strong"], answer: 0 },
        { id: 201, type: "text", title: "201. 잃다", word: "잃다", options: ["1. To lose", "2. To find", "3. To gain", "4. To keep"], answer: 0 },
        { id: 202, type: "text", title: "202. 지원금", word: "지원금", options: ["1. Subsidy / Support fund", "2. Tax", "3. Salary", "4. Fine"], answer: 0 },
        { id: 203, type: "text", title: "203. 최저임금", word: "최저임금", options: ["1. Minimum wage", "2. Maximum wage", "3. Average wage", "4. Bonus"], answer: 0 },
        { id: 204, type: "text", title: "204. 매년", word: "매년", options: ["1. Every year / Annually", "2. Every month", "3. Every week", "4. Every day"], answer: 0 },
        { id: 205, type: "text", title: "205. 바꾸다", word: "바꾸다", options: ["1. To change / Alter", "2. To keep", "3. To stop", "4. To start"], answer: 0 },
        { id: 206, type: "text", title: "206. 발표하다", word: "발표하다", options: ["1. To announce / Publish", "2. To hide", "3. To cancel", "4. To forbid"], answer: 0 },
        { id: 207, type: "text", title: "207. 만약", word: "만약", options: ["1. If / In case", "2. Although", "3. Because", "4. Therefore"], answer: 0 },
        { id: 208, type: "text", title: "208. 사업주", word: "사업주", options: ["1. Employer / Business owner", "2. Employee", "3. Customer", "4. Manager"], answer: 0 },
        { id: 209, type: "text", title: "209. 법", word: "법", options: ["1. Law / Act", "2. Rule", "3. Custom", "4. Habit"], answer: 0 },
        { id: 210, type: "text", title: "210. 어기다", word: "어기다", options: ["1. To break / Violate (a rule/law)", "2. To follow", "3. To protect", "4. To make"], answer: 0 },
        { id: 211, type: "text", title: "211. 한국인", word: "한국인", options: ["1. Korean (person)", "2. Foreigner", "3. Worker", "4. Employer"], answer: 0 },
        { id: 212, type: "text", title: "212. 똑같이", word: "똑같이", options: ["1. Equally / Exactly the same", "2. Differently", "3. Partially", "4. Roughly"], answer: 0 },
        { id: 213, type: "text", title: "213. 권리", word: "권리", options: ["1. Right (legal right)", "2. Duty", "3. Responsibility", "4. Rule"], answer: 0 },
        { id: 214, type: "text", title: "214. 낮다", word: "낮다", options: ["1. To be low", "2. To be high", "3. To be long", "4. To be short"], answer: 0 },
        { id: 215, type: "text", title: "215. 생각되다", word: "생각되다", options: ["1. To be thought / Considered", "2. To be forgotten", "3. To be known", "4. To be seen"], answer: 0 },
        { id: 216, type: "text", title: "216. 경우", word: "경우", options: ["1. Case / Situation", "2. Reason", "3. Result", "4. Purpose"], answer: 0 },
        { id: 217, type: "text", title: "217. 고객상담센터", word: "고객상담센터", options: ["1. Customer service center", "2. Police station", "3. Hospital", "4. Post office"], answer: 0 },
        { id: 218, type: "text", title: "218. 문의하다", word: "문의하다", options: ["1. Test", "2. To inquire / Ask", "3. To answer", "4. To order"], answer: 1 },
        { id: 219, type: "text", title: "219. 위반", word: "위반", options: ["1. Violation / Infringement", "2. Compliance", "3. Agreement", "4. Permission"], answer: 0 },
        { id: 220, type: "text", title: "220. 임금", word: "임금", options: ["1. Wages / Pay", "2. Tax", "3. Rent", "4. Price"], answer: 0 }
    ]
};
